name: Build and Release

on:
  push:
    branches: [ master ]
    tags: [ "v*" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create Build Directory
      run: mkdir -p build

    - name: Build with Xcode
      run: |
        xcodebuild \
          -project NetSpeedMonitor.xcodeproj \
          -scheme NetSpeedMonitor \
          -configuration Release \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO \
          CONFIGURATION_BUILD_DIR=build/Release \
          clean build

    - name: Ad-hoc Code Signing
      run: |
        codesign --force --deep --sign - "build/Release/NetSpeedMonitor.app"

    - name: Remove Attributes
      run: |
        xattr -cr "build/Release/NetSpeedMonitor.app"
        xattr -r -d com.apple.quarantine "build/Release/NetSpeedMonitor.app"
        xattr -r -d com.apple.metadata:kMDItemWhereFroms "build/Release/NetSpeedMonitor.app"

    - name: Package .app to .zip
      run: |
        cd build/Release
        zip -r NetSpeedMonitor.zip NetSpeedMonitor.app

    - name: Upload Artifacts (Master)
      if: github.ref == 'refs/heads/master'
      uses: actions/upload-artifact@v4
      with:
        name: build-${{ github.sha }}
        path: build/

    - name: Create Release Draft
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v2
      with:
        draft: true
        body_path: RELEASE_NOTES.MD
        files: |
          build/Release/NetSpeedMonitor.zip
          build/Release/NetSpeedMonitor.app
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
